### ISSUE TITLE
Make docker cloud project

### ISSUE THREAD

**Issue by dada513** [PrismarineJS/prismarine-web-client#127]
This will allow to pull the image from docker hub and not only build it. I need a maintainer to:
- create a project at https://hub.docker.com/repository/create
- set github repo in build settings
- with build settings: 
![image](https://user-images.githubusercontent.com/49000790/111913205-6249bc80-8a6d-11eb-82dd-2ed3fa25b97f.png)
- then click create and build

**Comment by rom1504** [comment]
https://hub.docker.com/repository/registry-1.docker.io/prismarinejs/prismarine-web-client/builds/2eff0451-6d6a-4a0a-97a6-b2e9855f19b0 running

**Comment by rom1504** [comment]
Failed @dada513

**Comment by rom1504** [comment]
You can make a pr to fix it

**Comment by dada513** [comment]
> Failed @dada513 

Can you copy me the error ? I don't have access

**Comment by rom1504** [comment]
https://github.com/docker/hub-feedback/issues/438

The fact you don't have access is not ok imo

Either we find a way to make these logs public either we use GitHub action

I think we should use GitHub action

**Comment by dada513** [comment]
> https://github.com/docker/hub-feedback/issues/438
> 
> 
> 
> The fact you don't have access is not ok imo
> 
> 
> 
> Either we find a way to make these logs public either we use GitHub action
> 
> 
> 
> I think we should use GitHub action

Yeah that would be probably better. Tho the docker image works on my machine ¯\_(ツ)_/¯

**Comment by rom1504** [comment]
That's the error 

```
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
ERROR in unable to locate '/app/config.json' glob
webpack 5.27.1 compiled with 1 error and 3 warnings in 100894 ms
[91mnpm[0m
[91m [0m
[91mERR![0m
[91m [0m
[91mcode[0m
[91m ELIFECYCLE
```

But I don't think we should fix it in this environment

I think we should setup GitHub action and fix any problem in the gh action env instead

Otherwise all future pull request will have this no access problem

**Comment by dada513** [comment]
#142 related
