### ISSUE TITLE
client side digging prediction

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-web-client#139]
remove the block when digging is finished, not when the servers says it

**Comment by Karang** [comment]
This is already done. https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/digging.js#L125
finishDigging is called by the setTimeout client side.

**Comment by rom1504** [comment]
@Karang ah yeah I should have been more precise. What is missing here is removing the rendered block at the end of digging on the client side without waiting for the server.

**Comment by Karang** [comment]
Closed in favor of https://github.com/PrismarineJS/prismarine-viewer/issues/173
