### ISSUE TITLE
walking on snow from a regular block doesnt show a difference on the screen

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/prismarine-web-client#144]
shouldn't it since it's a difference in height?

**Comment by Karang** [comment]
if its only 1 layer, snow doesnt have a bounding box, check vanilla

**Comment by u9g** [comment]
> if its only 1 layer, snow doesnt have a bounding box, check vanilla

nevermind thats right, but should the outline be shown for the whole block if its not a full block 

![](https://i.imgur.com/Bi9nvN4.png)

**Comment by Karang** [comment]
This has nothing to do with snow, all blocks have the same cursor shape, the prerequist is to extract the interaction bounding box https://github.com/PrismarineJS/prismarine-web-client/issues/96
