### ISSUE TITLE
Tab hangs after one of recent updates

### ISSUE THREAD

**Issue by Moondarker** [PrismarineJS/prismarine-web-client#146]
Reported by 2 contributors so far, tab randomly hangs for good - including dev tools, profiler, etc.

This one is hard to reproduce, and has nothing to do with resource allocation (Ryzen 5 3600/32 Gb/3070 and the system was mostly idle)

At first I thought it began when I installed web-client as PWA, but after further testing it doesn't seem to make any difference
Easiest way to trigger seems to be moving, digging and constantly changing target blocks

- [ ] Make sure the issue exists
- [ ] Isolate part of the code where it happens
- [ ] Fix it
- [ ] Make sure it's gone for good

It's important to make sure that this issue is actually a thing before blindly fixing it, however [here is my №1 suspect](https://github.com/PrismarineJS/prismarine-web-client/blob/accabc8629116ff903fb20a7016be29ccb853c61/index.js#L391) (once again, try to make it easily reproducible first)

**Comment by Karang** [comment]
Without testing, i can already tell by looking at the code at https://github.com/PrismarineJS/prismarine-web-client/blob/accabc8629116ff903fb20a7016be29ccb853c61/index.js#L391 that if `cursorBlock !== null` and `e.button !== 0` and `e.button !== 2` (for instance when `e.button === 1`) the loop will be infinite and never yield the event loop.

**Comment by rom1504** [comment]
This is fixed, but a better fix is mentioned at #138

**Comment by Moondarker** [comment]
I should've thought about middle click, this is probably the way it was triggered for me at least twice :$
