### ISSUE TITLE
make placing slower

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-web-client#159]
I think we need to wait 200ms between each place ?

**Comment by LINKdiscordd** [comment]
Just make a boolean that if true prevents it from placing another block again and use setTimeout to disable the boolean again

**Comment by rom1504** [comment]
yeah it's not hard to do

**Comment by Moondarker** [comment]
Notchian clients use 4 client ticks delay, so yep, 200ms

**Comment by Karang** [comment]
The correct way to do it is to call the update() of cursor.js in physicsTick instead of animate and add a counter for placing.

**Comment by u9g** [comment]
> The correct way to do it is to call the update() of cursor.js in physicsTick instead of animate and add a counter for placing.

oh okay, so if the counter > 0 then wait 200s before place?

**Comment by Karang** [comment]
No, count 4 ticks and allow placing again when it reach 4.

**Comment by ShrimpyStuff** [comment]
We can close this issue I think

**Comment by AwesomestCode** [comment]
Closed by #160
