### ISSUE TITLE
Turn it into a game

### ISSUE THREAD

**Issue by AwesomestCode** [PrismarineJS/prismarine-web-client#161]
https://discord.com/channels/413438066984747026/413438067471548427/825867082733322300

**Comment by DJStompZone** [comment]
Am I...? I think I'm missing something here. 
Turn what into a game, exactly? The game client?

**Comment by rom1504** [comment]
It's indeed a bad practice to link to discord only.
Can you copy the relevant information here @AwesomestCode ?

**Comment by DJStompZone** [comment]
I'm gonna go out on a limb and say no, he can't 😐
I'm still super confused what "turn it into a game" even means
