### ISSUE TITLE
Make login menu less ugly

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-web-client#165]
Now it's more like minecraft but it's pretty ugly
Things that can be done to make it better:
* [x] decrease the font size of input content
* [x] decrease the size of the form box
* [x] add padding between input boxes
* [x] add back an explanation on what "Prismarine Web Client" is (yes that's important, it's not obvious for new users)

(cc @KalmeMarq )

**Comment by rom1504** [comment]
current state 
![image](https://user-images.githubusercontent.com/2346494/112899283-3f10b400-90e2-11eb-8996-c148f9f32354.png)

**Comment by rom1504** [comment]
reverted 
![image](https://user-images.githubusercontent.com/2346494/112901935-b267f500-90e5-11eb-8926-867274426c97.png)

**Comment by rom1504** [comment]
I think it's kind of important that the first screen people see when coming to this demo looks good

**Comment by u9g** [comment]
move the buttons out of the corner to somewhere more visible

**Comment by u9g** [comment]
maybe for the above you can make the play button smaller and centered and then put the other two buttons around the play button?

**Comment by KalmeMarq** [comment]
> maybe for the above you can make the play button smaller and centered and then put the other two buttons around the play button?

Even if I made the play button smaller there would be no room for the link buttons to be around it.
![image](https://user-images.githubusercontent.com/55203647/112907426-c14ea780-90e5-11eb-8341-961e0f473d96.png)

**Comment by u9g** [comment]
imo box needs to be smaller for smaller resolutions @KalmeMarq

**Comment by host008** [comment]
i added about check pull requests not sure if it works tho because git won't let me clone(I cant even clone the main repo)

**Comment by y2k04** [comment]
Could make it use actual Mojang/Microsoft authentication apis? (To achieve valid UUIDs and connect to vanilla servers)

https://wiki.vg/Authentication

**Comment by rom1504** [comment]
We already do (through https://github.com/PrismarineJS/node-yggdrasil)
the problem is these APIs do not return CORS headers so it's not possible to use them in the browser, only in the server (hence the proxy)
however you are answering in the wrong issue, see #27

**Comment by y2k04** [comment]
> We already do (through https://github.com/PrismarineJS/node-yggdrasil) the problem is these APIs do not return CORS headers so it's not possible to use them in the browser, only in the server (hence the proxy) however you are answering in the wrong issue, see #27

What about modifying this: https://gist.github.com/y2k04/4c20f71ff79970b3ef653f55389429bd
It bypasses CORS headers but only for text based files.

**Comment by extremeheat** [comment]
> ### [<img alt="@y2k04" width="20" height="20" src="https://avatars.githubusercontent.com/u/29883287?s=60&amp;u=8ff4c9ff2193a8383464965fd9c09a3913ebe957&amp;v=4">](/y2k04) ** [y2k04](/y2k04)**

neither of those work, discuss in #27
