### ISSUE TITLE
directory for multiple pjs

### ISSUE THREAD

**Issue by fox3000foxy** [PrismarineJS/prismarine-web-client#167]

**Comment by Karang** [comment]
What would be the use of it ? if you want to connect multiple clients, just open a new tab.

**Comment by AwesomestCode** [comment]
I think you may have intended to post this issue on prismarine-viewer. Since we haven't received any clarification and as of right now it doesn't seem to make much sense, I'll close this issue here so as to remain organised. If you can clarify, please comment and I'll reopen the issue.
