### ISSUE TITLE
Make controls work on mobile somehow

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-web-client#17]
Everything already works on mobile except for controls.
Would be great if that could work too

**Comment by ShrimpyStuff** [comment]
hmm is there a way to figure out if people are using mobile cause if we have that we can just add buttons and a joystick like pe

**Comment by ShrimpyStuff** [comment]
wait no joystick so that makes it easy

**Comment by rom1504** [comment]
Yes it's definitely possible to detect that in js

**Comment by rom1504** [comment]
> <Karang> about virtual joysticks: https://yoannmoi.net/nipplejs/

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-viewer/blob/55022c70b88e42275a3ad4dc67e756d6bb1da7fe/viewer/lib/controls.js

**Comment by rom1504** [comment]
looking around now works

for movement, it's less obvious how to do it in a nice way

**Comment by rom1504** [comment]
![Screenshot_2021-03-21-11-59-57-496_com mojang minecraftpe](https://user-images.githubusercontent.com/2346494/111902298-2ac31c00-8a3d-11eb-9438-cf583222b8c1.jpg)

Do a similar ui as this

**Comment by zardoy** [comment]
> Do a similar ui as this

Hey! I have no idea why I didn't write it here before, however I think I implemented that ui some time ago: https://github.com/zardoy/another-game-with-ilya/blob/a16adf707da6607fd705f14c710c42974254c990/src/shared/interface/TouchControls.tsx

As I remember I finished the implementation, and it could handle inifinite amount of pointers (touches). You can still look it in action on mobile: http://staging.dimaka.love/

Though I almost forgot the entire implementation, I'm going to build library that would have this UI controls bundled. I can create pr after that if you don't mind.

Also, does anybody know, is there any game on the net with touch controls support? I'm just curious.

**Comment by rom1504** [comment]
@KalmeMarq did it
