### ISSUE TITLE
Pause menu

### ISSUE THREAD

**Issue by AwesomestCode** [PrismarineJS/prismarine-web-client#176]
(Equivalent to escape menu in normal MC)

**Comment by rom1504** [comment]
duplicate of #67

**Comment by AwesomestCode** [comment]
@rom1504 am confused: I thought that was for an options menu, not a pause menu

**Comment by rom1504** [comment]
there is only one in game menu

**Comment by AwesomestCode** [comment]
Don’t you have to click a button in the initial screen (where you select
singleplayer or multiplayer) for options in the Notchian client? Or am I
misremembering?

**Comment by rom1504** [comment]
there are several options and screens in the in game menu yeah

**Comment by AwesomestCode** [comment]
Are we just lumping them into a single issue?

**Comment by rom1504** [comment]
feel free to define good sub parts and comment in the issue
