### ISSUE TITLE
Make the server choice / auth menu less ugly

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-web-client#18]
Using modal input for this is not good.
Would be great to have a minecraft like menu for this

**Comment by Karang** [comment]
A simple form would be easier and allow to jump faster into the game.
We could also add a dropdown to select the version.

**Comment by rom1504** [comment]
Yeah

**Comment by louis030195** [comment]
also "Password (blank for offline)" non-technical people will mistake "offline" for singleplayer

**Comment by rom1504** [comment]
done, thanks @u9g
