### ISSUE TITLE
Storage leaks

### ISSUE THREAD

**Issue by antithug** [PrismarineJS/prismarine-web-client#195]
The web client doesn't seem to be releasing the threejs objects. I believe you have to 'dispose' of all the threejs objects (textures, materials, etc.) to get them to release the webgl data. With a big world, you can only play for a short time before the browser tab quits.

It looks like chunks are getting unloaded, but that just releases the prismarine chunk. If you look at the heap snapshots, the storage that leaks is the system/JSArrayBufferData, which I think is the webgl system data.  Everything else looks fine.

**Comment by Karang** [comment]
I haven't played long enough to notice anything, but indeed it seems plausible that a leak of the GL objects happen. This is more an issue for prismarine-viewer though.

**Comment by antithug** [comment]
I'll add it there. I did a quick search on 'dispose' in the viewer code, and I didn't get any hits.

**Comment by Karang** [comment]
Yes I confirm that there are none. We always dealt with short sessions in pviewer so it never was an issue. Now that we are starting to use it more (and as a client), dispose should definitely be added.

**Comment by Pandapip1** [comment]
This should probably be closed because there's an issue in pviewer (https://github.com/PrismarineJS/prismarine-viewer/issues/196). I also made a PR that fixes it (https://github.com/PrismarineJS/prismarine-viewer/pull/226).
