### ISSUE TITLE
Error when connecting via proxy

### ISSUE THREAD

**Issue by Cerulean-Code** [PrismarineJS/prismarine-web-client#207]
![image](https://user-images.githubusercontent.com/82993666/129409976-dfa2e743-4ec4-460b-8b6c-73209fb202e5.png)

**Comment by AwesomestCode** [comment]
Please make sure the proxy is a *PrismarineJS Browserify proxy*. It appears as if you're attempting to use an entirely different type of proxy. 
If you are indeed using a supported proxy, can you confirm which commit of webclient you're using to run the proxy, and a log from the proxy?

**Comment by Cerulean-Code** [comment]
I was using a socks5 proxy. 
Seems like this is a user error.

**Comment by AwesomestCode** [comment]
Yeah, you can't use a SOCKS proxy with Prismarine Web Client. Don't worry, that's a common mistake. If you're running Prismarine Web Client locally, you can leave the proxy field blank and it'll use the local computer as the proxy. However, I highly suggest you use the demo, which has a PrismarineJS proxy automatically filled in.
