### ISSUE TITLE
How do i play singleplayer from the web client?

### ISSUE THREAD

**Issue by Adithr123** [PrismarineJS/prismarine-web-client#218]

**Comment by rom1504** [comment]
![image](https://user-images.githubusercontent.com/2346494/135978101-54dc81c7-656f-42c6-b164-aa0fd73be4df.png)
Press Play

**Comment by Adithr123** [comment]
no, i mean singleplayer

**Comment by Adithr123** [comment]
My mistake.

**Comment by Adithr123** [comment]
ALso options button doesnt work on the server

**Comment by rom1504** [comment]
duplicate of https://github.com/PrismarineJS/prismarine-web-client/issues/47
