### ISSUE TITLE
What servers can i use?

### ISSUE THREAD

**Issue by Adithr123** [PrismarineJS/prismarine-web-client#225]

**Comment by gl91306** [comment]
example: blocksmc.com(i can join and login, but after im logged in it wont put me to main server. is it possible to switch between subservers?)

**Comment by Adithr123** [comment]
so all default exept for the server

**Comment by AwesomestCode** [comment]
> example: blocksmc.com(i can join and login, but after im logged in it wont put me to main server. is it possible to switch between subservers?) 

Most servers treat sub-servers as different dimensions/worlds on the same server and mineflayer/pviewer (￼￼what is used internally) behave weirdly when changing dimensions so I wouldn't be surprised if sub-servers didn't work properly

And yes, you can connect to any server mineflayer supports that is also in offline mode.
