### ISSUE TITLE
add forge support

### ISSUE THREAD

**Issue by AgentDeath253** [PrismarineJS/prismarine-web-client#232]
please add forge support

**Comment by Yasser1225** [comment]
you should try making a forge client for like atleast 1.18 and 1.12.2
# PLEASE IM DESPERATE

**Comment by zardoy** [comment]
A lot of effort, but the idea is cool. Can think of some layer of compatibility

**Comment by gwhizoftv** [comment]
What is a forge client? Sorry


Michael Glenn Williams

CTO
Book a meeting <https://meetings.hubspot.com/michael-glenn-williams2>
805-499-1994 <805499-1994>
***@***.***
totalvu.tv
14060 Marquesas Way, Marina Del Rey, CA
[image: linkedin]
<https://www.linkedin.com/in/michael-glenn-williams-45ab23228/>
