### ISSUE TITLE
Afk fishingf problem

### ISSUE THREAD

**Issue by mamadeba** [PrismarineJS/prismarine-web-client#237]
![image](https://user-images.githubusercontent.com/81771585/140507099-7fc681f2-702e-4923-8127-330dfafe6816.png)

**Comment by PondWader** [comment]
This does not look related to the web-client. It looks like this is an error you are getting with mineflayer ([https://github.com/prismarinejs/mineflayer](https://github.com/prismarinejs/mineflayer)). You may also receive better support in the PrismarineJS discord server.

**Comment by AwesomestCode** [comment]
This doesn’t seem related to prismarine-web-client. For help with Mineflayer or the Python bridge, please join the PrismarineJS discord server.
