### ISSUE TITLE
How do i load it into repl.it?

### ISSUE THREAD

**Issue by Adithr123** [PrismarineJS/prismarine-web-client#243]
![image](https://user-images.githubusercontent.com/85714072/140846663-784c021c-7687-40f6-8499-89369876402f.png)
This is what i get.

**Comment by AwesomestCode** [comment]
Looks like you're not able to install prismarine-web-client as a global module. You can try installing it to a random node project by adding it as a dependency and then running ``npx prismarine-web-client``. Alternatively, you can clone the repo as if you were working on it and then run it using the development instructions.

*Note: Discord is heavily preferred for support requests as many more people check that and with much more frequency compared to GitHub (still keep bug reports and feature requests here though)!*
