### ISSUE TITLE
Cant connect to web client

### ISSUE THREAD

**Issue by bobisnumber123** [PrismarineJS/prismarine-web-client#269]

**Comment by AwesomestCode** [comment]
Hello. Could you please give more details, such as which branch/commit you’re using, what server you’re trying to connect to (type), and steps for reproduction?

**Comment by bobisnumber123** [comment]
While I was trying to connect to 95.111.249.143:10000 I got stuck on the logging in screen so I also tried on java. This also didn't work. I also asked some of my friends to connect to the server and they couldn't either. So I don't know if it's the server or the web client.
