### ISSUE TITLE
chat not working (using latest release)

### ISSUE THREAD

**Issue by desplol** [PrismarineJS/prismarine-web-client#270]
https://github.com/PrismarineJS/prismarine-web-client/commit/1b08956d1071dfbcc0174471babc661c5a6f043c

![image](https://user-images.githubusercontent.com/96207058/149239754-eed46799-2263-47c9-b92b-f66e812bb801.png)

you can send messages to the server, but no clients can receive them

**Comment by AwesomestCode** [comment]
Closed by #272
