### ISSUE TITLE
Webclient won't load

### ISSUE THREAD

**Issue by Adithr123** [PrismarineJS/prismarine-web-client#276]
The web client doesnt connect, it only shows the connecting screen...

**Comment by wowsosososocool** [comment]
im having the same issue

**Comment by JVGA8837** [comment]
try changing the proxy to webmcproxy.glitch.me it worked for me.

**Comment by AwesomestCode** [comment]
@Adithr123 Is your issue solved?

**Comment by Codedelta2** [comment]
Yeah same here, doesn't load for me. It say logging... and it stay like that. I tried using this webmcproxy.glitch.me  instead of the original port, also didn't work. Any suggestions?

**Comment by AwesomestCode** [comment]
Console log please?

**Comment by william33s** [comment]
still says logging in not doing anything else

**Comment by AwesomestCode** [comment]
> still says logging in not doing anything else

Not helpful. Please give a console log.
