### ISSUE TITLE
Add slider for mouse sensitivity

### ISSUE THREAD

**Issue by AwesomestCode** [PrismarineJS/prismarine-web-client#28]
People are complaining that it's way too sensitive

**Comment by rom1504** [comment]
add a good default (would be great to figure out a good way to compute this)

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-web-client/commit/52df0ee8cf6259e6f688bb8dab01fead2b3d17eb lowered the default and exposed a property that could be used in ui

**Comment by AwesomestCode** [comment]
Closed by #257
