### ISSUE TITLE
How to run this on replit?

### ISSUE THREAD

**Issue by KogutGaming** [PrismarineJS/prismarine-web-client#282]
How to run this on replit?

**Comment by KogutGaming** [comment]
help me pls!

**Comment by autowert66** [comment]
Create a new Bash Repl, 
create a `replit.nix` file and paste this:
```nix
{ pkgs }: {
    deps = [
        pkgs.bashInteractive
        pkgs.nodejs-16_x
    ];
}
```
This will install nodejs 16.

Then install `prismarine-web-client` with 
```bash
npm i prismarine-web-client
```
(in the Terminal).

Now paste this into `main.sh`:
```bash
npx prismarine-web-client
```

Then just click the Run-Button.

**Comment by KogutGaming** [comment]
thx :D

**Comment by KogutGaming** [comment]
and where i can find proxy for this?

**Comment by KogutGaming** [comment]
is any mods for this which is working on replit?

**Comment by autowert66** [comment]
What do you mean by `mods`?

**Comment by autowert66** [comment]
What do you mean by `mods`?

**Comment by KogutGaming** [comment]
addons which add more things

**Comment by rom1504** [comment]
no

**Comment by AwesomestCode** [comment]
There aren’t any add-ons available for Prismarine Web Client. Also, for longer discussion questions, I’d highly recommend going into our Discord.

**Comment by AwesomestCode** [comment]
Looks like this question is solved; closing
