### ISSUE TITLE
socket closed 

### ISSUE THREAD

**Issue by cool3453345fdsgr** [PrismarineJS/prismarine-web-client#291]
it keeps saying socket closed so can y'all help me fix this because im trying to play this at school on my chromebook

**Comment by AwesomestCode** [comment]
Hello! Please provide a console log indicating the error. We can't help you troubleshoot without a log.

**Comment by william33s** [comment]
whats a console log?

**Comment by AwesomestCode** [comment]
Also, this is a duplicate of #288. Please move any further conversation to there.
