### ISSUE TITLE
Wierd Bugs

### ISSUE THREAD

**Issue by TheBalkanDev** [PrismarineJS/prismarine-web-client#295]
1. On Linux and Windows (Chrome Browser) the Jumping is very buggy.
2. On Mobile (Chrome & Firefox) the Controls are like this
3. The „Chat“ and „Options“ Buttons aren’t working on Mobile.

![0A029A18-D7DB-4F76-A702-960211537708](https://user-images.githubusercontent.com/75144786/163209682-dd54828d-d2bb-4c7c-9763-e97d69e0e521.png)
![933AD93B-2521-418B-A503-7DAD9E206CF0](https://user-images.githubusercontent.com/75144786/163209739-94077b49-52ab-44b7-8d81-44d1b70c4c98.png)

**Comment by AwesomestCode** [comment]
Can you make separate issues for each? Thanks

**Comment by AwesomestCode** [comment]
Closing issue for now as separate bug reports should be filed.
