### ISSUE TITLE
Mineweb Test Server Kicking Issue

### ISSUE THREAD

**Issue by TheAmericanHacker001** [PrismarineJS/prismarine-web-client#296]
The Test Server for the Minecraft Web Client keeps kicking repeatedly, showing this message....
![Screenshot 2022-04-18 12 02 55 PM](https://user-images.githubusercontent.com/103959233/163861270-81052399-9453-4065-959e-5dba988a31b5.png)

**Comment by EJD799** [comment]
That is happening for me, too! (on every server)

**Comment by A-Random-Person-on-Github** [comment]
[Uploading prismarine-web-client-master.zip…]()

**Comment by TheAmericanHacker001** [comment]
could you let me know through email when it works again? Thank you

**Comment by TheAmericanHacker001** [comment]
thank you :) its been a long time but im glad its up again
