### ISSUE TITLE
I had opened an issue #299 and accidentally closed it

### ISSUE THREAD

**Issue by AndyGames531** [PrismarineJS/prismarine-web-client#300]
https://github.com/PrismarineJS/prismarine-web-client/issues/299#issuecomment-1118120234

replying to this

if you meant my replit console log here it is after pressing ctrl+shift+i

https://user-images.githubusercontent.com/82985435/166859026-91b87373-9358-4bf5-9960-1d821923edd3.mp4

I dont think this is what you meant, so i have the web client console logs here
![Screenshot 2022-05-04 11 12 10 PM](https://user-images.githubusercontent.com/82985435/166859109-d040dab8-8fda-448a-a399-64fa70c9739d.png)

**Comment by AwesomestCode** [comment]
Please don’t spam the repo with multiple issues reports for the same problem—you can reopen the previous issue instead. Can you copy the text here to a comment there?
