### ISSUE TITLE
Small changes to client (Minecraft Commons or Minecraft Basics)

### ISSUE THREAD

**Issue by RepeatGitHub** [PrismarineJS/prismarine-web-client#310]
It's crazy to think that I could connect to a Minecraft server through a web browser, and I love how this project does that so well! However, there's a few small things that could be cool to see implemented:

- Inventory/Hotbar (I bet a ton of ppl ask this already, but it's a big thing)
- Being able to see dropped items and/or items that other players are holding
- Entity mapping issues (Cow is good, but mobs like pigs/sheep have their textures mapped to the wrong parts of their model)
- Camera changes (Making client-side camera move downwards when crouching, maybe also having screen turn a bit red temporarily after taking damage)
- Texture/hitbox fixes (Dark Oak Logs look like Acacia Logs, able to fly 1/2 block by standing on certain slabs, etc.)
- Make entities turn red temporarily after being losing health

Again, love the project, keep going with it man!

**Comment by AwesomestCode** [comment]
That’s definitely a bug, but dying in general is not recommended right now since it’s really buggy all around.

**Comment by RepeatGitHub** [comment]
Alright, I'll go make an issue for that bug then
