### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by BestAutumn7583** [PrismarineJS/prismarine-web-client#314]
When I used Microsoft Edge to join the 1.18.2 server, the blocks of Y<0 don't display properly.
Make the Debug screen can display more information & add all debug-keys if you can.
DO YOUR BEST!
THANKS.

**Comment by AwesomestCode** [comment]
The first issue is a pviewer issue; could you please open an issue there?

Can you also please open a separate issue (it’s easier to track with separate issues for each feature) for the debug screen (if it doesn’t already exist)?

Thanks
