### ISSUE TITLE
Cannot connect to any server

### ISSUE THREAD

**Issue by interpixle** [PrismarineJS/prismarine-web-client#337]
I cant connect to anything, i tried connecting to like 5 different servers, i even left default options and hit play and it just says logging in forever and then sometimes gets an error. How do i actually get in the game?

**Comment by CobbleShop** [comment]
> 

Hard to tell. WHAT is the error? What are you trying to do? Show the code. Did you install everything correctly? Which versions are you using?

**Comment by interpixle** [comment]
i am using the official webclient.

**Comment by CobbleShop** [comment]
> i am using the official webclient.

still didn't quite reply to what i was asking. :D

**Comment by SamuelPozzobon** [comment]
Supports up to 1.17.1, using the default proxy of the official webclient.

Works only in servers with offline mode.

**Comment by interpixle** [comment]
That makes sense. Still doesnt explain why i cant even connect to the default server but the offline mode thing makes sense. Thanks!
