### ISSUE TITLE
dmca notice

### ISSUE THREAD

**Issue by Connorppeach** [PrismarineJS/prismarine-web-client#345]
Hi I had created a fork of this a while back and just now I have revived a dmca takedown request claiming to be from a enforcment agent for mojang AB 
in the request they ask all forks be taken down as well as "https://github.com/PrismarineJS/prismarine-web-client" 
they also claim 

---"
This user has presumably decompiled and reverse engineered portions of our code to find how to recreate the game. They have leveraged several historical versions of the game as well as other common libraries which are all laid out in the credits documentation.

Their code goes against our EULA and Terms of Use by disabling and allowing unauthenticated connections to servers as well as redistribution the client for local game play
"---

furthermore 
they even claim this is not under an open source licence
---"
**Is the work licensed under an open source license?**

No
"---
they also mention eagle craft for some reason 

what is the status on this and other than taking down the fork what should I do.

best regards,
Connor Peach

**Comment by rom1504** [comment]
The DMCA notice wrongly claim this is using EaglerCraft which it is not.
We have submitted a counter notice.

You can decide to do the same at https://github.com/contact/dmca

**Comment by rom1504** [comment]
Solved
