### ISSUE TITLE
It's Only A Blackscreen

### ISSUE THREAD

**Issue by Lostguestsneeze** [PrismarineJS/prismarine-web-client#349]
The Web Client Shows Only Black Nothing Else https://prismarinejs.github.io/prismarine-web-client/

**Comment by extremeheat** [comment]
Try https://d60kl4rmeuiuq.cloudfront.net/

**Comment by Lostguestsneeze** [comment]
still
No Work

**Comment by gwhizoftv** [comment]
In the console it gives this error about the wrong node version on the server:
index.js?896bae8a75c9913a668b:179 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
9195 @ index.js?896bae8a75c9913a668b:179
__webpack_require__ @ index.js?896bae8a75c9913a668b:1564
(anonymous) @ index.js?896bae8a75c9913a668b:1564
(anonymous) @ index.js?896bae8a75c9913a668b:1564
(anonymous) @ index.js?896bae8a75c9913a668b:1564
index.js?896bae8a75c9913a668b:1564 Your node version is currently 14.0.0
11313 @ index.js?896bae8a75c9913a668b:1564
__webpack_require__ @ index.js?896bae8a75c9913a668b:1564
(anonymous) @ index.js?896bae8a75c9913a668b:1564
(anonymous) @ index.js?896bae8a75c9913a668b:1564
(anonymous) @ index.js?896bae8a75c9913a668b:1564
index.js?896bae8a75c9913a668b:1564 Please update it to a version >= 18.x.x from https://nodejs.org/
11313 @ index.js?896bae8a75c9913a668b:1564
__webpack_require__ @ index.js?896bae8a75c9913a668b:1564
(anonymous) @ index.js?896bae8a75c9913a668b:1564
(anonymous) @ index.js?896bae8a75c9913a668b:1564
(anonymous) @ index.js?896bae8a75c9913a668b:1564
index.js?896bae8a75c9913a668b:1564 Uncaught TypeError: i.exit is not a function
    at 11313 (index.js?896bae8a75c9913a668b:1564:1203964)
    at __webpack_require__ (index.js?896bae8a75c9913a668b:1564:26507217)
    at index.js?896bae8a75c9913a668b:1564:26508704
    at index.js?896bae8a75c9913a668b:1564:26517339
    at index.js?896bae8a75c9913a668b:1564:26517343
11313 @ index.js?896bae8a75c9913a668b:1564
__webpack_require__ @ index.js?896bae8a75c9913a668b:1564
(anonymous) @ index.js?896bae8a75c9913a668b:1564
(anonymous) @ index.js?896bae8a75c9913a668b:1564
(anonymous) @ index.js?896bae8a75c9913a668b:1564

**Comment by ZXMushroom63** [comment]
I get a blackscreen too, but the console says that "NodeJS is outdated, update to 18.x.x"

**Comment by ljcool2006** [comment]
Same here, I have the latest LTS of Node.js, yet it still loads Node.js 14.0.0 for some reason.
