### ISSUE TITLE
tcp connection closed

### ISSUE THREAD

**Issue by Scratch2033YT** [PrismarineJS/prismarine-web-client#367]
I have a minecraft server running in offline mode this happend the logs says "Scratch2033YT **(IP HIDDEN)** lost connection: You are not white-listed on this server!" how can i fix this

**Comment by extremeheat** [comment]
Are you allowed to be on the server and can you connect with a vanilla client?

**Comment by extremeheat** [comment]
Reopen if you have more info

**Comment by Scratch2033YT** [comment]
vanilla client: can connect

> Reopen if you have more info

cant reopen

**Comment by Scratch2033YT** [comment]
and forgot to note: i am whitelisted, AND it is running in aternos
