### ISSUE TITLE
chat

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-web-client#4]

**Comment by rom1504** [comment]
https://github.com/AwesomestCode/mineflayer-web-test/blob/main/chat.js but doesn't work by default, needs fixing
@circuit10 @AwesomestCode

**Comment by AwesomestCode** [comment]
Do you mean that the chat system doesn't work by default or something else?

**Comment by rom1504** [comment]
yes

**Comment by AwesomestCode** [comment]
Will do.

**Comment by rom1504** [comment]
now there, but it's ugly, would be best to make it less ugly

**Comment by AwesomestCode** [comment]
Could you please attach a screenshot showing which parts are ugly?

**Comment by rom1504** [comment]
![image](https://user-images.githubusercontent.com/2346494/109403403-9f82c900-795d-11eb-93d9-568ac9227387.png)

* html horizontal and vertical scrollers
* chat stays displayed when not chatting
* font too big ?

**Comment by rom1504** [comment]
nothing urgent though ;)

**Comment by AwesomestCode** [comment]
Not supposed to look like that. I'm bad at UX design, but not *that bad*. Did you copy over the fonts and other assets from the MineWeb repo?

**Comment by rom1504** [comment]
Good enough for now
