### ISSUE TITLE
run a websocket proxy somewhere and do a github page demo ?

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-web-client#5]

**Comment by rom1504** [comment]
This could work well with these features:
* Host static client in GitHub page
* Make it possible to target any websocket proxy (give the choice to the user in the client)
* Provide a short list of websocket proxies that are hosted by people

That way the client always works as long as there is at least one websocket proxy working

I'll set this up I think

**Comment by rom1504** [comment]
For auth it can either go through the proxy either ask the user to send his token

**Comment by AwesomestCode** [comment]
Let's keep auth in a separate issue since it's a bit different (plus the fact that I sort of want to handle auth once I finish inventory): #13

**Comment by rom1504** [comment]
We have a demo now but still worth having also this static demo

**Comment by rom1504** [comment]
how : 
1. patch net-browserify for cors ; make it point to the right thing
2. don't use net browserify and use websocket and http proxy ourselves

**Comment by Karang** [comment]
1. done
Next steps are:
* hosting a proxy that accept cors requests (not behind cloudflare or configure it properly)
* deploying to github pages (setting the proxy to the right default value)

**Comment by rom1504** [comment]
hosting the proxy is done, deploying to gh pages too

remaining is doing the automated gh pages deployment

we need to make it so it builds then amend and push force to gh pages

**Comment by rom1504** [comment]
todo:
* [ ] add option using webpack DefinePlugin to pass a default proxy
* [ ] write yml autodeploy file
  * [ ] run webpack to generate public
  * [ ] copy public outside of current folder
  * [ ] checkout gh-pages
  * [ ] git rm -rf *
  * [ ] copy files of public/* to .
  * [ ] git add .
  * [ ] git commit --amend -m "updated"
  * [ ] use https://github.com/ad-m/github-push-action to push

**Comment by Karang** [comment]
done
