### ISSUE TITLE
Tell the user when a disconnect occurs

### ISSUE THREAD

**Issue by AwesomestCode** [PrismarineJS/prismarine-web-client#50]
It looks like it's buggy when you suddenly stop being able to move. If it takes me 5 seconds to realise that no, my code isn't bugged, it just disconnected, we can expect a normal user to think that too.
This is especially important as we are about to implement auto-update for the demo, which will make it frequently restart.

**Comment by AwesomestCode** [comment]
Can be implemented by just un-hiding the loading screen and changing the text to "You have been disconnected. Press the ANY key to continue."

**Comment by rom1504** [comment]
done
