### ISSUE TITLE
Implement breaking animation

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-web-client#59]
at least have the same animation as vanilla
currently from an user perspective, it's not clear whether it works

* [ ] breaking animation

**Comment by AwesomestCode** [comment]
Didn't we end up deciding to implement this directly in PrismarineJS/prismarine-viewer?

**Comment by rom1504** [comment]
yes that would make sense
we can still track it here, it should work here too

**Comment by rom1504** [comment]
more information there https://discord.com/channels/413438066984747026/815363216947150879/820844110574911499

**Comment by AwesomestCode** [comment]
I'm still working on it.

**Comment by rom1504** [comment]
great
