### ISSUE TITLE
Better placing

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-web-client#60]
Make sure it works, it seems to be buggy atm

**Comment by AwesomestCode** [comment]
It seems like it works for me. It's much clearer with hotbar added—though it's buggy near spawn, presumably due to spawn protection.

**Comment by rom1504** [comment]
ok, will close this when it feels like minecraft, currently it feels broken without hotbar

**Comment by rom1504** [comment]
basic functionality is there (hotbar, outline), let's open another one for fully fledged placing
