### ISSUE TITLE
Find a better name

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-web-client#68]
prismarine-web-client is too long and boring.
Characteristics of the new name:
* fast to type
* easy to remember
* fun ?

What ideas do you have?

**Comment by rom1504** [comment]
some ideas:
* mcweb
* pwc
* wwwmc
* browser-minecraft
* non descriptive : fast-ant (http://rom1504.github.io/adjective-animal/)

**Comment by AwesomestCode** [comment]
Project Arachne

**Comment by KaffinPX** [comment]
Projekt Arachne: The Game

**Comment by AwesomestCode** [comment]
Opération Clever Spider

**Comment by rom1504** [comment]
let's keep this name
