### ISSUE TITLE
GET https://webclient.prismarine.js.org/favicon.ico 404

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/prismarine-web-client#73]
![](https://i.imgur.com/sfbR2BZ.png)

**Comment by rom1504** [comment]
what logo should we use ?

**Comment by EasyClifton** [comment]
The GH repo one looks nice

**Comment by u9g** [comment]
dirt block

**Comment by Karang** [comment]
prismarine block ?

**Comment by rom1504** [comment]
https://raw.githubusercontent.com/PrismarineJS/marketing-and-media/d9183395950e8eae0e6db6a3df85c713df37838c/Logos%20and%20Icons/SVG%20files/prismarinejs.svg ?

**Comment by AwesomestCode** [comment]
Minecraft uses a crafting table, let's use a furnace.

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-web-client/pull/77

**Comment by rom1504** [comment]
fixed
