### ISSUE TITLE
make menu nicer looking 

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-web-client#76]
https://freefrontend.com/css-forms/

**Comment by u9g** [comment]
imo something like this looks great https://codepen.io/soufiane-khalfaoui-hassani/pen/LYpPWda , but we would just put more lines and maybe for like the server line we can make the box 80% then have a small space then for 15% of the line we can have a port box prefilled with 25565

**Comment by rom1504** [comment]
feel free to try it out
just change https://github.com/PrismarineJS/prismarine-web-client/blob/master/lib/menu.js
and run npm start to check the result

**Comment by u9g** [comment]
done in https://github.com/PrismarineJS/prismarine-web-client/pull/82
