### ISSUE TITLE
Improve hotbar

### ISSUE THREAD

**Issue by Karang** [PrismarineJS/prismarine-web-client#84]
- [x] Add numbers of items on top of the icon
- [x] Display name of the item above the hotbar for 2s when switching item, then fade away (can use tween for that)
- [x] Use a texture atlas to display the item icons
- [x] Move hotbar code in its own file
- [ ] Implement off-hand slot (press F to exchange items)

**Comment by rom1504** [comment]
I'm working on moving that to lit element currently fyi

**Comment by Karang** [comment]
![image](https://user-images.githubusercontent.com/1977472/111092743-368f7980-8537-11eb-8cb8-b577ebf09d4c.png)
In firefox, items are offset a bit, and the images have a small gray border.

**Comment by Karang** [comment]
I fixed firefox issues and improved a bit the css.

**Comment by rom1504** [comment]
I think this is done (basic hotbar improvements), created https://github.com/PrismarineJS/prismarine-web-client/issues/158 for the last missing point
