### ISSUE TITLE
chat bug

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/prismarine-web-client#88]
If I click t to open chat, click something on another window, then come back, I won't be able to come back even If I click esc until I click t again and type a message, then everything starts working again

**Comment by AwesomestCode** [comment]
How does it work in Vanilla?

**Comment by u9g** [comment]
when you tab out and then come back,  you are still in the chat box, but then if you click escape everything closes and you are back in your game. also you cant scroll in ur hotbar while in chat

**Comment by AwesomestCode** [comment]
Are we even able to detect Escape key presses? I think the browser intercepts those and takes you out of full screen and stuff.

**Comment by u9g** [comment]
> Are we even able to detect Escape key presses? I think the browser intercepts those and takes you out of full screen and stuff.

is there an event for exiting fullscreen?

**Comment by rom1504** [comment]
works fine here
